sonar.organization=quiestce-iut
sonar.projectKey=QuiEstCe-IUT_BUT-R3.01-SAE

sonar.sources=public,src,core
sonar.tests=tests
sonar.exclusions=vendor/**,coverage/**,database/**

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.sourceEncoding=UTF-8
